name: interact
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python>=3.11
  - pip:
      - albumentations
      - opencv-python
      - imageio
      - imageio-ffmpeg
      - pytorch-lightning
      - omegaconf
      - test-tube
      - streamlit
      - einops
      - torch-fidelity
      - git+https://github.com/openai/CLIP.git
      - protobuf
      - torchmetrics
      - torch==2.4.0+cu118 
      - torchaudio==2.4.0+cu118 
      - torchvision==0.19.0+cu118
      - transformers
      - kornia
      - xformers==v0.0.28.post1
      - gradio==3.36.1  # new gradio fail in load bounding box from examples
      - gradio-client==0.2.9

variables:
  TF_CPP_MIN_LOG_LEVEL: 1
  OMP_NUM_THREADS: 10